<?php

namespace Soga\FacturacionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeFacturasRepository extends EntityRepository
{   
    /**
     * Devuelve los registros de los detalles de factura
     * @param string $strNumero Consecutivo de la factura
     * @return type Objeto de tipo query de la clase facturas detalle
     */
    public function DevDqlFacturaDetalle($strNumero) {
        $em = $this->getEntityManager();         
        $dql = "SELECT defactura FROM SogaFacturacionBundle:DeFacturas defactura WHERE defactura.nrofactura = " . $strNumero;
        $objQuery = $em->createQuery($dql);       
        return $objQuery;                
    }    
}