<?php

namespace Soga\FacturacionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacConfiguracionRepository extends EntityRepository
{   

}