<?php

namespace Soga\FacturacionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturasRepository extends EntityRepository
{   
    /**
     * Devuelve los registros de comprobantes sin exportar
     * @return type Objeto de tipo query de la clase factura
     */
    public function DevDqlFacturasSinExportar($strDesde = "", $strHasta = "") {
        $em = $this->getEntityManager();         
        $dql = "SELECT facturas FROM SogaFacturacionBundle:Facturas facturas WHERE facturas.exportadoContabilidad = 0";
        if($strDesde != "") {
           $dql = $dql . " AND facturas.fechaini >='". $strDesde ."'" ;
        }
        if($strHasta != "") {
           $dql = $dql . " AND facturas.fechaini <='". $strHasta ."'" ;
        }
        $objQuery = $em->createQuery($dql);       
        return $objQuery;                
    }    
}