security:
    firewalls:                
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path:  login
                check_path:  login_check                

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        in_memory:
            memory:
                users:
                    mario:  { password: 70143086, roles: 'ROLE_USER' }
                    ana:  { password: ana2015, roles: 'ROLE_USER' }
                    walter:  { password: walter2015, roles: 'ROLE_USER' }
                    ana: { password: kitten, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext