parameters:
#    soga_nomina.example.class: Soga\NominaBundle\Example

services:
#    soga_nomina.example:
#        class: %soga_nomina.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
