parameters:
#    soga_front_end.example.class: Soga\FrontEndBundle\Example

services:
#    soga_front_end.example:
#        class: %soga_front_end.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
