parameters:
#    soga_seguridad.example.class: Soga\SeguridadBundle\Example

services:
#    soga_seguridad.example:
#        class: %soga_seguridad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
