<?php

namespace Soga\ContabilidadBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaestroComprobantesRepository extends EntityRepository
{   
    /**
     * Devuelve los registros de comprobantes sin exportar
     * @return type Objeto de tipo query de la clase maestro comprobantes
     */
    public function DevDqlComprobantesSinExportar($strDesde = "", $strHasta = "") {
        $em = $this->getEntityManager();         
        $dql = "SELECT maestrocomprobantes FROM SogaContabilidadBundle:MaestroComprobantes maestrocomprobantes WHERE (maestrocomprobantes.tipop = 'NOMINA' OR maestrocomprobantes.tipop = 'PRIMAS' OR maestrocomprobantes.tipop = 'PRESTACIONES' OR maestrocomprobantes.tipop = 'PRESTACION') AND maestrocomprobantes.exportadoContabilidad = 0";
        if($strDesde != "") {
           $dql = $dql . " AND maestrocomprobantes.fechapago >='". $strDesde ."'" ;
        }
        if($strHasta != "") {
           $dql = $dql . " AND maestrocomprobantes.fechapago <='". $strHasta ."'" ;
        }
        $objQuery = $em->createQuery($dql);       
        return $objQuery;                
    }    
}