<?php

namespace Soga\NominaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentroRepository extends EntityRepository
{   
    public function devTarifaSalud($strIdentificacion) {
        $em = $this->getEntityManager();     
        $douTarifaSalud = 0;
        $arCentro = new \Soga\NominaBundle\Entity\Centro();
        $arCentro = $em->getRepository('SogaNominaBundle:Centro')->findOneBy(array('cedemple' => $strIdentificacion));                        
        if(count($arCentro) > 0) {
            $arDecentro = new \Soga\NominaBundle\Entity\Decentro();
            $arDecentro = $em->getRepository('SogaNominaBundle:Decentro')->findOneBy(array('codcentro' => $arCentro->getCodcentro(), 'codsala' => '51'));                                    
            if(count($arDecentro) > 0) {
                $douTarifaSalud = $arDecentro->getPorcentaje();
            }
        }
        return $douTarifaSalud;               
    }      
}