<?php

namespace Soga\NominaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DenominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratoRepository extends EntityRepository
{             
    public function devDqlContratosPeriodo($fechaDesde = "", $fechaHasta = "") {
        $em = $this->getEntityManager();         
        $dql = "SELECT contrato FROM SogaNominaBundle:Contrato contrato "
                . "WHERE (contrato.fechater >= '" . $fechaDesde . "' OR contrato.fechater = '0000-00-00') AND contrato.fechainic <='" . $fechaHasta . "'";       
        $objQuery = $em->createQuery($dql);  
        $arContratos = $objQuery->getResult();
        return $arContratos;                
    }            
}