<?php

namespace Soga\NominaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmpleadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpleadoRepository extends EntityRepository
{   
    public function DevDqlEmpleadosSinExportar() {
        $em = $this->getEntityManager();         
        $dql = "SELECT empleado FROM SogaNominaBundle:Empleado empleado WHERE empleado.exportadoContabilidad = 0";
        $objQuery = $em->createQuery($dql);       
        return $objQuery;                
    }        
}