<?php

namespace Soga\NominaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaestroReciboRepository extends EntityRepository
{   
    /**
     * Devuelve los registros de nomina sin exportar
     * @return type Objeto de tipo query de la clase nomina
     */
    public function DevDqlMaestrosRecibosSinExportar($strDesde = "", $strHasta = "") {
        $em = $this->getEntityManager();           
        $dql = "SELECT marecibo FROM SogaNominaBundle:MaestroRecibo marecibo WHERE marecibo.exportadoContabilidad = 0 AND (marecibo.idrecibo = 1 OR marecibo.idrecibo = 2) ";
        if($strDesde != "") {
           $dql = $dql . " AND marecibo.fechaRa >='". $strDesde ."'" ;
        }
        if($strHasta != "") {
           $dql = $dql . " AND marecibo.fechaRa <='". $strHasta ."'" ;
        }
        $objQuery = $em->createQuery($dql);       
        return $objQuery;                
    }    
}