<?php

namespace Soga\NominaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NominaRepository extends EntityRepository
{   
    /**
     * Devuelve los registros de nomina sin exportar
     * @return type Objeto de tipo query de la clase nomina
     */
    public function DevDqlNominaSinExportar($strDesde = "", $strHasta = "") {
        $em = $this->getEntityManager();         
        $dql = "SELECT nomina FROM SogaNominaBundle:Nomina nomina WHERE nomina.exportadoContabilidad = 0";
        if($strDesde != "") {
           $dql = $dql . " AND nomina.fechaDesde >='". $strDesde ."'" ;
        }
        if($strHasta != "") {
           $dql = $dql . " AND nomina.fechaDesde <='". $strHasta ."'" ;
        }
        $objQuery = $em->createQuery($dql);       
        return $objQuery;                
    }    
    
    public function dqlNominaSinProcesar($strDesde = "", $strHasta = "") {
        $em = $this->getEntityManager();         
        $dql = "SELECT nomina FROM SogaNominaBundle:Nomina nomina WHERE nomina.procesoAuxiliar = 0";
        if($strDesde != "") {
           $dql = $dql . " AND nomina.fechaDesde >='". $strDesde ."'" ;
        }
        if($strHasta != "") {
           $dql = $dql . " AND nomina.fechaDesde <='". $strHasta ."'" ;
        }        
        return $dql;                
    }    
}