<?php

namespace Soga\NominaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomRegistroExportacionRepository extends EntityRepository
{   
   /** 
    * Devuelve el registro de exportacion segun la cuenta y el consecutivo
    * @param string $strConsecutivo Consecutivo de la nomina
    * @param string $strCuenta Cuenta que afecta
    * @return integer Registro de exportacion
    */
   public function DevRegistroExportacion($strConsecutivo, $strCuenta ) {
        $intCodigoRegistroExportacion = 0;
        $em = $this->getEntityManager();
        $arNomRegistroExportacion = new \Soga\NominaBundle\Entity\NomRegistroExportacion();        
        $arNomRegistroExportacion = $em->getRepository('SogaNominaBundle:NomRegistroExportacion')->findOneBy(array('consecutivo' => $strConsecutivo, 'cuenta' => $strCuenta));        

        if(count($arNomRegistroExportacion) > 0) {
            $intCodigoRegistroExportacion = $arNomRegistroExportacion->getCodigoRegistroExportacionPk();
        }
        return $intCodigoRegistroExportacion; 
   }
}