<?php

namespace Soga\NominaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrimaRepository extends EntityRepository
{   
    /**
     * Devuelve los registros de nomina sin exportar
     * @return type Objeto de tipo query de la clase nomina
     */
    public function DevDqlPrimasSinExportar($strDesde = "", $strHasta = "") {
        $em = $this->getEntityManager();         
        $dql = "SELECT prima FROM SogaNominaBundle:Prima prima WHERE prima.exportadoContabilidad = 0";
        if($strDesde != "") {
           $dql = $dql . " AND prima.fechaP >='". $strDesde ."'" ;
        }
        if($strHasta != "") {
           $dql = $dql . " AND prima.fechaP <='". $strHasta ."'" ;
        }
        $objQuery = $em->createQuery($dql);       
        return $objQuery;                
    }    
}