<?php

namespace Soga\NominaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReciboRepository extends EntityRepository
{   
    /**
     * Devuelve los registros de nomina sin exportar
     * @return type Objeto de tipo query de la clase nomina
     */
    public function DevDqlDetalleRecibo($strConsecutivo) {
        $em = $this->getEntityManager();         
        $dql = "SELECT recibo FROM SogaNominaBundle:Recibo recibo WHERE recibo.nroCaja = " . $strConsecutivo;
        $objQuery = $em->createQuery($dql);       
        return $objQuery;                
    }      
}