<?php

namespace Soga\NominaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReciboRepository extends EntityRepository
{   
    /**
     * Devuelve los registros de nomina sin exportar
     * @return type Objeto de tipo query de la clase nomina
     */
    public function DevDqlRecibosSinExportar($strDesde = "", $strHasta = "") {
        $em = $this->getEntityManager();         
        $dql = "SELECT recibo FROM SogaNominaBundle:Recibo recibo WHERE recibo.exportadoContabilidad = 0";
        if($strDesde != "") {
           $dql = $dql . " AND recibo.fechaRe >='". $strDesde ."'" ;
        }
        if($strHasta != "") {
           $dql = $dql . " AND recibo.fechaRe <='". $strHasta ."'" ;
        }
        $objQuery = $em->createQuery($dql);       
        return $objQuery;                
    }    
}