<?php

namespace Soga\NominaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SsoPeriodoDetalleRepository extends EntityRepository
{   
    public function DevDqlPeriodos() {
        $em = $this->getEntityManager();         
        $dql = "SELECT periododetalle FROM SogaNominaBundle:SsoPeriodoDetalle periododetalle WHERE periododetalle.anio = 2015 "
                . "AND periododetalle.estadoCerrado = 0";
        $objQuery = $em->createQuery($dql);       
        return $objQuery;                
    }    
}