<?php

namespace Soga\NominaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SsoPeriodoRepository extends EntityRepository
{   
    public function DevDqlPeriodos() {
        $em = $this->getEntityManager();         
        $dql = "SELECT periodo FROM SogaNominaBundle:SsoPeriodo periodo WHERE periodo.anio = 2015";
        $objQuery = $em->createQuery($dql);       
        return $objQuery;                
    }    
}