<?php

namespace Soga\NominaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrasladoEpsRepository extends EntityRepository
{   

    public function trasladoPeriodoEmpleado($fechaDesde = "", $fechaHasta = "", $strNumeroIdentificacion) {
        $em = $this->getEntityManager();         
        $dql = "SELECT te FROM SogaNominaBundle:TrasladoEps te "
                . "WHERE te.fechaInicioTraslado >= '" . $fechaDesde . "' "
                . "AND te.fechaInicioTraslado <= '" . $fechaHasta . "' "
                . "AND te.cedemple = '" . $strNumeroIdentificacion . "' ";       
        $objQuery = $em->createQuery($dql);  
        $arTrasladoEps = $objQuery->getResult();
        return $arTrasladoEps;                
    }    

    public function aplicacionTrasladoPeriodoEmpleado($fechaDesde = "", $fechaHasta = "", $strNumeroIdentificacion) {
        $em = $this->getEntityManager();         
        $dql = "SELECT te FROM SogaNominaBundle:TrasladoEps te "
                . "WHERE te.fechaAplicacionTraslado >= '" . $fechaDesde . "' "
                . "AND te.fechaAplicacionTraslado <= '" . $fechaHasta . "' "
                . "AND te.cedemple = '" . $strNumeroIdentificacion . "' ";       
        $objQuery = $em->createQuery($dql);  
        $arTrasladoEps = $objQuery->getResult();
        return $arTrasladoEps;                
    }        
}