<?php

namespace Soga\NominaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacacionProgramadaRepository extends EntityRepository
{   
    public function devDqlVacaciones($fechaDesde = "", $fechaHasta = "", $strNumeroIdentificacion) {
        $em = $this->getEntityManager();         
        $dql = "SELECT vacaciones FROM SogaNominaBundle:VacacionProgramada vacaciones "
                . "WHERE vacaciones.hasta >= '" . $fechaDesde . "' AND vacaciones.desde <='" . $fechaHasta . "' "
                . "AND vacaciones.cedemple = '" . $strNumeroIdentificacion . "' ";       
        $objQuery = $em->createQuery($dql);  
        $arVacaciones = $objQuery->getResult();
        return $arVacaciones;                
    }             
}